### Recuperar BLOGS
GET http://localhost:3001/api/blogs


### Recuperar BLOG
GET http://localhost:3001/api/blogs/4


### Crear un blog POST
POST http://localhost:3001/api/blogs
Content-Type: application/json
Accept: */*

{
  name: "Diego Mesa",
  number: "040-123456333",
}

### Eliminar blog por ID
DELETE http://localhost:3001/api/blogs/4

